#!/bin/sh
# Code generated by binstaller. DO NOT EDIT.
#
set -e
usage() {
  this=$1
  cat <<EOF
$this: download ${NAME} from ${REPO}

Usage: $this [-b bindir] [-d] [tag]
  -b sets bindir or installation directory, Defaults to ./bin
  -d turns on debug logging
   [tag] is a tag from
   https://github.com/charmbracelet/gum/releases
   If tag is missing, then the latest will be used.

 Generated by binstaller
  https://github.com/haya14busa/binstaller
EOF
  exit 2
}

cat /dev/null <<EOF
------------------------------------------------------------------------
https://github.com/client9/shlib - portable posix shell functions
Public domain - http://unlicense.org
https://github.com/client9/shlib/blob/master/LICENSE.md
but credit (and pull requests) appreciated.
------------------------------------------------------------------------
EOF
is_command() {
  command -v "$1" >/dev/null
}
echoerr() {
  echo "$@" 1>&2
}
_logp=6
log_set_priority() {
  _logp="$1"
}
log_priority() {
  if test -z "$1"; then
    echo "$_logp"
    return
  fi
  [ "$1" -le "$_logp" ]
}
log_tag() {
  case $1 in
    0) echo "emerg" ;;
    1) echo "alert" ;;
    2) echo "crit" ;;
    3) echo "err" ;;
    4) echo "warning" ;;
    5) echo "notice" ;;
    6) echo "info" ;;
    7) echo "debug" ;;
    *) echo "$1" ;;
  esac
}
log_debug() {
  log_priority 7 || return 0
  echoerr "$(log_prefix)" "$(log_tag 7)" "$@"
}
log_info() {
  log_priority 6 || return 0
  echoerr "$(log_prefix)" "$(log_tag 6)" "$@"
}
log_err() {
  log_priority 3 || return 0
  echoerr "$(log_prefix)" "$(log_tag 3)" "$@"
}
log_crit() {
  log_priority 2 || return 0
  echoerr "$(log_prefix)" "$(log_tag 2)" "$@"
}
uname_os() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    msys*) os="windows" ;;
    mingw*) os="windows" ;;
    cygwin*) os="windows" ;;
  esac
  if [ "$os" = "sunos" ]; then
    if [ "$(uname -o)" = "illumos" ]; then
      os="illumos"
    else
      os="solaris"
    fi
  fi
  echo "$os"
}
uname_arch() {
  arch=$(uname -m)
  case $arch in
    x86_64) arch="amd64" ;;
    i86pc) arch="amd64" ;;
    x86) arch="386" ;;
    i686) arch="386" ;;
    i386) arch="386" ;;
    aarch64) arch="arm64" ;;
    armv5*) arch="armv5" ;;
    armv6*) arch="armv6" ;;
    armv7*) arch="armv7" ;;
  esac
  echo "${arch}"
}
uname_os_check() {
  os=$(uname_os)
  case "$os" in
    darwin) return 0 ;;
    dragonfly) return 0 ;;
    freebsd) return 0 ;;
    linux) return 0 ;;
    android) return 0 ;;
    midnightbsd) return 0 ;;
    nacl) return 0 ;;
    netbsd) return 0 ;;
    openbsd) return 0 ;;
    plan9) return 0 ;;
    solaris) return 0 ;;
    illumos) return 0 ;;
    windows) return 0 ;;
  esac
  log_crit "uname_os_check '$(uname -s)' got converted to '$os' which is not a GOOS value. Please file bug at https://github.com/client9/shlib"
  return 1
}
uname_arch_check() {
  arch=$(uname_arch)
  case "$arch" in
    386) return 0 ;;
    amd64) return 0 ;;
    arm64) return 0 ;;
    armv5) return 0 ;;
    armv6) return 0 ;;
    armv7) return 0 ;;
    ppc64) return 0 ;;
    ppc64le) return 0 ;;
    mips) return 0 ;;
    mipsle) return 0 ;;
    mips64) return 0 ;;
    mips64le) return 0 ;;
    s390x) return 0 ;;
    amd64p32) return 0 ;;
  esac
  log_crit "uname_arch_check '$(uname -m)' got converted to '$arch' which is not a GOARCH value.  Please file bug report at https://github.com/client9/shlib"
  return 1
}
http_download_curl() {
  local_file=$1
  source_url=$2
  header=$3
  if [ -z "$header" ]; then
    curl -fsSL -o "$local_file" "$source_url"
  else
    curl -fsSL -H "$header" -o "$local_file" "$source_url"
  fi
}
http_download_wget() {
  local_file=$1
  source_url=$2
  header=$3
  if [ -z "$header" ]; then
    wget -q -O "$local_file" "$source_url"
  else
    wget -q --header "$header" -O "$local_file" "$source_url"
  fi
}
http_download() {
  log_debug "http_download $2"
  if is_command curl; then
    http_download_curl "$@"
    return
  elif is_command wget; then
    http_download_wget "$@"
    return
  fi
  log_crit "http_download unable to find wget or curl"
  return 1
}
http_copy() {
  tmp=$(mktemp)
  http_download "${tmp}" "$1" "$2" || return 1
  body=$(cat "$tmp")
  rm -f "${tmp}"
  echo "$body"
}
github_release() {
  owner_repo=$1
  version=$2
  test -z "$version" && version="latest"
  giturl="https://github.com/${owner_repo}/releases/${version}"
  json=$(http_copy "$giturl" "Accept:application/json")
  test -z "$json" && return 1
  version=$(echo "$json" | tr -s '\n' ' ' | sed 's/.*"tag_name":"//' | sed 's/".*//')
  test -z "$version" && return 1
  echo "$version"
}
cat /dev/null <<EOF
------------------------------------------------------------------------
End of functions from https://github.com/client9/shlib
------------------------------------------------------------------------
EOF


hash_sha256() {
  TARGET=${1:-/dev/stdin}
  if is_command gsha256sum; then
    hash=$(gsha256sum "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command sha256sum; then
    hash=$(sha256sum "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command shasum; then
    hash=$(shasum -a 256 "$TARGET" 2>/dev/null) || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command openssl; then
    hash=$(openssl dgst -sha256 "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 2
  else
    log_crit "hash_sha256 unable to find command to compute sha-256 hash"
    return 1
  fi
}

hash_verify() {
  hash_verify_internal "$1" "$2" hash_sha256
}


untar() {
  tarball=$1
  strip_components=${2:-0} # default 0
  case "${tarball}" in
  *.tar.gz | *.tgz) tar --no-same-owner -xzf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar.xz) tar --no-same-owner -xJf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar.bz2) tar --no-same-owner -xjf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar) tar --no-same-owner -xf "${tarball}" --strip-components "${strip_components}" ;;
  *.gz) gunzip "${tarball}" ;;
  *.zip)
    # unzip doesn't have a standard --strip-components
    # Workaround: extract to a subdir and move contents up if stripping
    if [ "$strip_components" -gt 0 ]; then
      extract_dir=$(basename "${tarball%.zip}")_extracted
      unzip -q "${tarball}" -d "${extract_dir}"
      # Move contents of the *first* directory found inside extract_dir up
      # This assumes wrap_in_directory=true convention
      first_subdir=$(find "${extract_dir}" -mindepth 1 -maxdepth 1 -type d -print -quit)
      if [ -n "$first_subdir" ]; then
        # Move all contents (* includes hidden files)
        mv "${first_subdir}"/* .
        # Optionally remove the now-empty subdir and the extract_dir
        rmdir "${first_subdir}"
        rmdir "${extract_dir}"
      else
        log_warn "Could not find subdirectory in zip to strip components from ${extract_dir}"
        # Files are extracted in current dir anyway, proceed
      fi
    else
      unzip -q "${tarball}"
    fi
    ;;
  *)
    log_err "untar unknown archive format for ${tarball}"
    return 1
    ;;
  esac
}

extract_hash() {
  TARGET=$1
  checksums=$2
  if [ -z "$checksums" ]; then
    log_err "extract_hash checksum file not specified in arg2"
    return 1
  fi
  BASENAME=${TARGET##*/}
  grep -E "([[:space:]]|/|\*)${BASENAME}$" "${checksums}" 2>/dev/null | tr '\t' ' ' | cut -d ' ' -f 1
}

hash_verify_internal() {
  TARGET_PATH=$1
  SUMFILE=$2
  HASH_FUNC=$3
  if [ -z "${SUMFILE}" ]; then
    log_err "hash_verify_internal checksum file not specified in arg2"
    return 1
  fi
  if [ -z "${HASH_FUNC}" ]; then
    log_err "hash_verify_internal hash func not specified in arg3"
    return 1
  fi
  got=$($HASH_FUNC "$TARGET_PATH")
  if [ -z "${got}" ]; then
    log_err "failed to calculate hash: ${TARGET_PATH}"
    return 1
  fi
  # 1) “hash-only” line?
  if grep -i -E "^${got}[[:space:]]*$" "$SUMFILE" >/dev/null 2>&1; then
    return 0
  fi
  # 2) Check hash & file name match
  want=$(extract_hash "${TARGET_PATH}" "${SUMFILE}")
  if [ "$want" != "$got" ]; then
    log_err "hash_verify checksum for '$TARGET_PATH' did not verify ${want} vs ${got}"
    return 1
  fi
}


# --- Embedded Checksums (Format: VERSION:FILENAME:HASH) ---
EMBEDDED_CHECKSUMS="
0.15.0:gum_0.15.0_Windows_x86_64.zip.sbom.json:978f82c8d288a6fa1f804b1a6261a8254a17a2840a97e663c6e4303c16f460e2
0.15.0:gum_0.15.0_Netbsd_armv6.tar.gz.sbom.json:7d50e4136cf557804978deb0f05350c2a76f627e3fc519c48a351abbf4c36c43
0.15.0:gum_0.15.0_aarch64.apk:d32487583c4a5ff48fa31e64e78d5e63625ceee12629fbc3d00d215b6c2e6842
0.15.0:gum_0.15.0_x86.apk:55bd11dfb221a26138fcb17bb51245bbecc01c8628e67ad5e010343d7001b8b3
0.15.0:gum_0.15.0_Linux_arm64.tar.gz.sbom.json:68c99ee231b0208519195d746fb2610163e5443bd9459f73f4856068e00a230d
0.15.0:gum_0.15.0_Netbsd_i386.tar.gz.sbom.json:1420833ccbbc4a6e1f1acbb55d3d61d4f2913599c8b2317ffe971bb2d0048499
0.15.0:gum_0.15.0_Linux_i386.tar.gz:64569a0938ba2a7bd2d98509ebcfb6374decabaa04b31ca9a81f90e2233e8ca5
0.15.0:gum_0.15.0_Darwin_arm64.tar.gz.sbom.json:14dc7c111801f0e9fb9038d6a608f0930aba43aaa23379368fb58ccd31c4e795
0.15.0:gum_0.15.0_Freebsd_armv6.tar.gz.sbom.json:2100f8c754d1f2708aac4a1d64cf4eeb2e138719a8a1ce21fba0f3268bdce464
0.15.0:gum_0.15.0_Openbsd_i386.tar.gz.sbom.json:ce9eecec3b095db4858d3c6964ec05712768eae6fbe2a762d62ecb9b017da095
0.15.0:gum_0.15.0_Openbsd_x86_64.tar.gz.sbom.json:f33d67d012e08284f4b3c9c786fb0728a260983fb4d12b5f512156ad753171f4
0.15.0:gum-0.15.0-1.i386.rpm:9dec645895840d73d53ac6e5515874ec2c386f14fe7259c8f460a25b244d10c1
0.15.0:gum_0.15.0_Freebsd_i386.tar.gz.sbom.json:fc88399b66a430c364a6c5fed87b0f91597efe15bff870f59f8dad673a990e65
0.15.0:gum_0.15.0_Windows_i386.zip:ee330cd87e72297317c798bbb72bd6a619e02976526c40a6f19051250639a03d
0.15.0:gum-0.15.0-1.armv7hl.rpm:b2adf8d94dfb163962f18f07a3fd5e289ae700451b3f080ee0f412f2e6374356
0.15.0:gum_0.15.0_Freebsd_armv7.tar.gz:b86bb294622078e1c47c688fdcb6c9cb2f43c939ad9172def16102e5166d2b69
0.15.0:gum_0.15.0_Netbsd_arm64.tar.gz.sbom.json:c93a21e1d6eb7e861e704ddfb6fe7854aea6cf92962ddbe6f52a7a41608c3e2d
0.15.0:gum_0.15.0_Openbsd_armv7.tar.gz:3b068204c5b32dbc0e61c0a8b85c801b654d158c70f604b87de2ebe0316d9339
0.15.0:gum_0.15.0_Openbsd_i386.tar.gz:f1f91c3db8593d02d273026722bb5c97096a332ebb970295f8a6ee2790d2b7d3
0.15.0:gum_0.15.0_Windows_i386.zip.sbom.json:8ff24c64dea55adb5feec14dfe2140e7c57a0a0c5be7dcaefc30d0343d8612f0
0.15.0:gum_0.15.0_Freebsd_armv6.tar.gz:90ea02b7e80e589c10233fdd444c04f62cae00c0366fbdc005fbcbf7641699fd
0.15.0:gum_0.15.0_Linux_armv7.tar.gz.sbom.json:5fd17d64c8931a3ab6be8f942ae60f4781b494f3db74794fe9777f6936870a65
0.15.0:gum_0.15.0_Openbsd_armv6.tar.gz:33b4bd736239caec9538feb7c1d2d9966b314af66a36d09ce27b36d6e34f9ac9
0.15.0:gum_0.15.0_Openbsd_armv6.tar.gz.sbom.json:b9776d3892c1dc35a5bea7eb21d56841588d89fc0eb0dcf3d10f13bb5bc9a966
0.15.0:gum_0.15.0_Linux_arm64.tar.gz:307bd78ee12e7265fa2971db6ebf9caf56cfec2f07cad66e044d400d7bcdc905
0.15.0:gum_0.15.0_Darwin_x86_64.tar.gz:cfb0817c7ef97adb703ecc946a150a2db8a3aa847c5896c2a3237014396c5f69
0.15.0:gum_0.15.0_Freebsd_arm64.tar.gz.sbom.json:9adc779ad1e8d41b1dd925b05f4815c059d55df43176d4628181623e51b7a559
0.15.0:gum_0.15.0_Linux_x86_64.tar.gz:97ead0ccab4320ac310bf6a3b6497dd48e583cba7d73fc723e7d0b4e94da6799
0.15.0:gum_0.15.0_Linux_x86_64.tar.gz.sbom.json:93bfa649647c7b3cfaa7555fb174be8d62c66218bd8ca3df8a1280df201a06a6
0.15.0:gum-0.15.0.tar.gz.sbom.json:420a6c6f303e69996fd1624a6cb9fe7cb5bad520afe6e2b2f836b003993e486e
0.15.0:gum_0.15.0_Linux_armv7.tar.gz:101e5c5ceafd04ee250720be29c4173cbc9f54390eecb1a6ceda2a39591c351e
0.15.0:gum_0.15.0_Netbsd_x86_64.tar.gz.sbom.json:50a922f281304254e941b1eaa3a390bde7d9f7ab77341f732451666d324f0c2f
0.15.0:gum_0.15.0_armhf.deb:8945776b4cbc993e0b3953e63eab853dc8c994daac2af9c3e8e8a2f35e794080
0.15.0:gum_0.15.0_Freebsd_armv7.tar.gz.sbom.json:0b180c7f35ad22699b482a74bd54f1ec26cbfbe731c3475bd5c6cc1f548be83d
0.15.0:gum_0.15.0_Freebsd_x86_64.tar.gz:f7c1aad623d9dbcdad78ea17bf04785c09f6aaa1e013588ec0451a4c84aba3bd
0.15.0:gum_0.15.0_Linux_armv6.tar.gz.sbom.json:1738f4e03d2418c6074d798b57047970c6244a782cccf2f17e2970a3cb3a9ee9
0.15.0:gum_0.15.0_Netbsd_armv7.tar.gz:39291e791e44a42cdcab85cde57c6433a8f0bbfd5a204f1b14daa354f3ba4a93
0.15.0:gum_0.15.0_Openbsd_x86_64.tar.gz:e92ad1c0def6820d37050e6238c18d0107634a216749d523156b075b46d02d26
0.15.0:gum_0.15.0_arm64.deb:d92acfa67794b6067724fbb860987cdd5da68f2e61d402ff413c10a33dc60489
0.15.0:gum_0.15.0_armv7.apk:0691338d461f9f160c8d6999b6265eaa00b975a8e04927ce6199077d28c6db08
0.15.0:gum_0.15.0_x86_64.apk:e3bd6192ea49b1d1ea0df73b38f74b8d794018f66fe9921ea34b9a4ac7f0010f
0.15.0:gum-0.15.0-1.x86_64.rpm:1765edf30f83e4fb66286826cf709df14b31dc6bfd1e314529e6d0949d5b8be8
0.15.0:gum_0.15.0_Freebsd_i386.tar.gz:d2c3755c1719c9bc26ef5b9ab30f4259c7dc7c38042d5db45e63739f8f963722
0.15.0:gum_0.15.0_Linux_armv6.tar.gz:68d2549a348349e83bebde8af93322824d22e986650a9c1128af595ccb6c92e3
0.15.0:gum_0.15.0_Darwin_arm64.tar.gz:82c5d460e5ba1366be26a890bb9275f5336c7fba403376ccc246aab5c19ed7ea
0.15.0:gum_0.15.0_Darwin_x86_64.tar.gz.sbom.json:0a5b3b29f7892034b98ff824d9fb9dc08753d8c388448b9084f2f8958879f05b
0.15.0:gum_0.15.0_Freebsd_x86_64.tar.gz.sbom.json:a4d3fecd0fcd505748f8ac5bc0e397553dd71aa8905cbd6df24c98092c514d4d
0.15.0:gum_0.15.0_Netbsd_arm64.tar.gz:4d103c68088289db2c94c4da427c6e20fb1a17201f4631b1084503c350e6a425
0.15.0:gum_0.15.0_Netbsd_x86_64.tar.gz:5e29ac4a6d47fcae3773359282a954e01ab9db582cae9dd4ab0172003a256a99
0.15.0:gum_0.15.0_Windows_x86_64.zip:f7f62cb40823272269e693494a12082275d6adffe8ef30d92277da5895396c85
0.15.0:gum_0.15.0_Netbsd_armv7.tar.gz.sbom.json:3701d195a5cf5fa677285f313ca75a4ff70ef462c3965291d50e33eb3d8b8b1b
0.15.0:gum_0.15.0_Netbsd_i386.tar.gz:29268b7d1be30e5f1473da5b6d7414feb2b35517221576d962d43fe6df85ede6
0.15.0:gum_0.15.0_Openbsd_armv7.tar.gz.sbom.json:dfae91c423f0db27efc19f081208a1e9904c81a7c6e832581754f8b50a169819
0.15.0:gum_0.15.0_Netbsd_armv6.tar.gz:34b46a8c58848d17f6aa72cd7a5c7f153ba9478355d7ebff1e0e46a4fe4529af
0.15.0:gum_0.15.0_amd64.deb:96b3173531781b3616e84ed851f7d111306b48ff25697823ac6a18ca31cc1bec
0.15.0:gum_0.15.0_armhf6.deb:5b8981d175a33a56d6be2009a182382617c936b2f71b15b4a384a8aa1142ccea
0.15.0:gum-0.15.0.tar.gz:edbbb931024fb28da42bde07c70cc64b2a22a7953f429da643cddc9e3f12c63f
0.15.0:gum_0.15.0_Openbsd_arm64.tar.gz.sbom.json:ce6dedaf0c934c47bdbf0aec7f9b9a895e054bdb7ef44f3833aa07dbfd0d87b9
0.15.0:gum_0.15.0_Freebsd_arm64.tar.gz:d42c5c813d216feba9e19af3cbedc057b2c21ac7c469f779fc3e38983276500b
0.15.0:gum_0.15.0_Linux_i386.tar.gz.sbom.json:78124ed7de650ef499162f07e7886be13ccd79256edfcadc131146f4c7aafa73
0.15.0:gum_0.15.0_Openbsd_arm64.tar.gz:ffe134c3680f37c7200714b989342d217197c286458032981d7b32c544c8230c
0.15.0:gum_0.15.0_armhf.apk:993f2db93ca3f6bb157bcd28582b007f3db5f49044d92637200a0acac341f696
0.15.0:gum_0.15.0_i386.deb:d0477b1bc931fbf44c735389d958be2412a1fb18b36e1ba1ba9fc6bbf522d2a8
0.15.0:gum-0.15.0-1.aarch64.rpm:4f7d8f05ea64663442e8b858fed6d87214ee96ee0342b0fa0faa84ad8f71a26b
0.15.0:gum-0.15.0-1.armv6hl.rpm:a7b30c29e35bc6e9daafd1c982e32dc6450d5c288846367b332cff4d9e46b34e"

# Find embedded checksum for a given version and filename
find_embedded_checksum() {
  version="$1"
  filename="$2"
  echo "$EMBEDDED_CHECKSUMS" | grep -E "^${version}:${filename}:" | cut -d':' -f3
}

parse_args() {
  BINDIR="${BINSTALLER_BIN:-${HOME}/.local/bin}"
  while getopts "b:dqh?x" arg; do
    case "$arg" in
    b) BINDIR="$OPTARG" ;;
    d) log_set_priority 10 ;;
    q) log_set_priority 3 ;;
    h | \?) usage "$0" ;;
    x) set -x ;;
    esac
  done
  shift $((OPTIND - 1))
  TAG="${1:-v0.16.0}"
}

tag_to_version() {
  if [ "$TAG" = "latest" ]; then
    log_info "checking GitHub for latest tag"
    REALTAG=$(github_release "${REPO}" "${TAG}") && true
    test -n "$REALTAG" || {
      log_crit "Could not determine latest tag for ${REPO}"
      exit 1
    }
  else
    # Assume TAG is a valid tag/version string
    REALTAG="$TAG"
  fi
  if test -z "$REALTAG"; then
    log_crit "unable to find '${TAG}' - use 'latest' or see https://github.com/${REPO}/releases for details"
    exit 1
  fi
  VERSION=${REALTAG#v} # Strip leading 'v'
  TAG="$REALTAG"       # Use the resolved tag
  log_info "Resolved version: ${VERSION} (tag: ${TAG})"
}



resolve_asset_filename() {
  
  # --- Apply Rules ---
  ASSET_FILENAME=""
  if [ "${UNAME_ARCH}" = 'amd64' ] && true
  then
    ARCH='x86_64'
  fi
  if [ "${UNAME_OS}" = 'darwin' ] && true
  then
    OS='Darwin'
  fi
  if [ "${UNAME_OS}" = 'linux' ] && true
  then
    OS='Linux'
  fi
  if [ "${UNAME_OS}" = 'windows' ] && true
  then
    OS='Windows'
  fi
  if [ "${UNAME_OS}" = 'windows' ] && true
  then
    EXT='.zip'
  fi
  if [ -z "${ASSET_FILENAME}" ]; then
    ASSET_FILENAME="gum_${VERSION}_${OS}_${ARCH}${EXT}"
  fi
}

execute() {
  STRIP_COMPONENTS=1
  CHECKSUM_FILENAME="checksums.txt"

  # --- Construct URLs ---
  GITHUB_DOWNLOAD="https://github.com/${REPO}/releases/download"
  ASSET_URL="${GITHUB_DOWNLOAD}/${TAG}/${ASSET_FILENAME}"
  CHECKSUM_URL=""
  if [ -n "$CHECKSUM_FILENAME" ]; then
    CHECKSUM_URL="${GITHUB_DOWNLOAD}/${TAG}/${CHECKSUM_FILENAME}"
  fi

  # --- Download and Verify ---
  TMPDIR=$(mktemp -d)
  trap 'rm -rf -- "$TMPDIR"' EXIT HUP INT TERM
  log_debug "Downloading files into ${TMPDIR}"
  log_info "Downloading ${ASSET_URL}"
  http_download "${TMPDIR}/${ASSET_FILENAME}" "${ASSET_URL}"

  # Try to find embedded checksum first
  EMBEDDED_HASH=$(find_embedded_checksum "$VERSION" "$ASSET_FILENAME")

  if [ -n "$EMBEDDED_HASH" ]; then
    log_info "Using embedded checksum for verification"
    
    # Verify using embedded hash
    got=$(hash_sha256 "${TMPDIR}/${ASSET_FILENAME}")
    if [ "$got" != "$EMBEDDED_HASH" ]; then
      log_crit "Checksum verification failed for ${ASSET_FILENAME}"
      log_crit "Expected: ${EMBEDDED_HASH}"
      log_crit "Got: ${got}"
      return 1
    fi
    log_info "Checksum verification successful"
  elif [ -n "$CHECKSUM_URL" ]; then
    # Fall back to downloading checksum file
    log_info "Downloading checksums from ${CHECKSUM_URL}"
    http_download "${TMPDIR}/${CHECKSUM_FILENAME}" "${CHECKSUM_URL}"
    log_info "Verifying checksum ..."
    hash_verify "${TMPDIR}/${ASSET_FILENAME}" "${TMPDIR}/${CHECKSUM_FILENAME}"
  else
    log_info "No checksum found, skipping verification."
  fi

  if [ -z "${EXT}" ] || [ "${EXT}" = ".exe" ]; then
    log_debug "Target is raw binary"
  else
    log_info "Extracting ${ASSET_FILENAME}..."
    (cd "${TMPDIR}" && untar "${ASSET_FILENAME}" "${STRIP_COMPONENTS}")
  fi
  BINARY_NAME='gum'
  if [ -z "${EXT}" ] || [ "${EXT}" = ".exe" ]; then
    BINARY_PATH="${TMPDIR}/${ASSET_FILENAME}"
  else
    BINARY_PATH="${TMPDIR}/gum"
  fi

  if [ "${UNAME_OS}" = "windows" ]; then
    case "${BINARY_NAME}" in *.exe) ;; *) BINARY_NAME="${BINARY_NAME}.exe" ;; esac
    case "${BINARY_PATH}" in *.exe) ;; *) BINARY_PATH="${BINARY_PATH}.exe" ;; esac
  fi

  if [ ! -f "${BINARY_PATH}" ]; then
    log_crit "Binary not found: ${BINARY_PATH}"
    log_crit "Listing contents of ${TMPDIR} ..."
    if command -v find >/dev/null 2>&1; then
      cd "${TMPDIR}" && find .
    else
      cd "${TMPDIR}" && ls -R .
    fi
    return 1
  fi

  # Install the binary
  INSTALL_PATH="${BINDIR}/${BINARY_NAME}"
  log_info "Installing binary to ${INSTALL_PATH}"
  test ! -d "${BINDIR}" && install -d "${BINDIR}"
  install "${BINARY_PATH}" "${INSTALL_PATH}"
  log_info "${BINARY_NAME} installation complete!"
}

# --- Configuration  ---
NAME='gum'
REPO='charmbracelet/gum'
EXT='.tar.gz'

# use in logging routines
log_prefix() {
  echo "${REPO}"
}

parse_args "$@"

# --- Determine target platform ---
OS="${BINSTALLER_OS:-$(uname_os)}"
UNAME_OS="${OS}"

ARCH="${BINSTALLER_ARCH:-$(uname_arch)}"
UNAME_ARCH="${ARCH}"
log_info "Detected Platform: ${OS}/${ARCH}"

# --- Validate platform ---
uname_os_check "$OS"
uname_arch_check "$ARCH"

tag_to_version

resolve_asset_filename

execute
